baseURL: https://ntemple.github.io
languageCode: en-us
title: Nick Temple
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Title Sup bruh 😎
    Content: This is something shows in your homepage.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/ntemple"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/thoughtmeister"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Nick Temple"
  contact: "nick@nicktemple.com"
  feedlinks: true
  copyright: "&copy2022 Nick Temple
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
